server:
  port: 8095

jwt:
  enabled: true
  issuer: ""
  audience: ""
  jwkUrl: "http://localhost:8080/auth/realms/sunbird-rc/protocol/openid-connect/certs"
  claimsNamespacePath: "$.realm_access.roles"

addverbAuthorizationUrl: "http://localhost:7081/wes/group/get-all-user-group?instanceCode={instanceCode}"

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: http_bin_anything_route
          uri: http://httpbin.org
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - name: AddRequestHeader
              args:
                name: X-Request-Foo
                value: Value!
          predicates:
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
            - Path=/anything