server:
  port: ${SERVER_PORT:8095}

#hcx headers
protocol:
  headers:
    mandatory: ${protocol_mandatory_headers:x-hcx-sender_code, x-hcx-recipient_code, x-hcx-api_call_id, x-hcx-timestamp, x-hcx-correlation_id}
    optional: ${protocol_optional_headers:x-hcx-workflow_id, x-hcx-debug_flag, x-hcx-error_details, x-hcx-debug_details, x-hcx-status}
headers:
  jose: ${jose_headers:alg, enc}

#hcx error headers
error:
  headers:
    mandatory: ${error_mandatory_headers:x-hcx-status, x-hcx-sender_code, x-hcx-recipient_code, x-hcx-error_details}
    optional: ${error_optional_headers:x-hcx-workflow_id, x-hcx-api_call_id}

timestamp:
  range: ${timestamp_range:10000}

jwt:
  enabled: ${JWT_ENABLED:true}
  issuer: ${JWT_ISSUER:}
  audience: ${JWT_AUDIENCE:}
  jwkUrl: ${JWT_JWK_URL:http://localhost:8080/auth/realms/sunbird-rc/protocol/openid-connect/certs}
  claimsNamespacePath: ${JWT_NS_PATH:$.realm_access.roles}

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}

registry:
  basePath: ${REGISTRY_BASE_PATH:http://localhost:8081}

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: hcx-api-route
          uri: ${HCX_API_BASEPATH:http://localhost:8080}
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - CachingRequestBodyFilter
            - HCXValidationFilter
          predicates:
            - Path=/v1/coverageeligibility/**, /v1/preauth/**, /v1/claim/**, /v1/paymentnotice/**, /v1/hcx/**

        - id: hcx-api-route-audit
          uri: ${HCX_API_BASEPATH:http://localhost:8080}
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - CachingRequestBodyFilter
            - AuditValidationFilter
          predicates:
            - Path=/v1/audit/search

        - id: hcx-registry-api-route
          uri: ${HCX_API_BASEPATH:http://localhost:8080}
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
          predicates:
            - Path=/participant/**, /health, /service/health
