server:
  port: ${server_port:8095}

jwt:
  enabled: ${jwt_enabled:false}
  issuer: ${jwt_issuer:}
  audience: ${jwt_audience:}
  jwkUrl: ${jwt_jwkUrl:http://localhost:8080/auth/realms/sunbird-rc/protocol/openid-connect/certs}
  claimsNamespacePath: ${jwt_nsPath:"$.realm_access.roles"}

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: protocol-service-route
          uri: ${hcx_api_basePath:localhost:8080}
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
          predicates:
            - Path=/v1/coverageeligibility/**, /v1/preauth/**, /v1/claims/**, /v1/paymentnotice/**, /health, /service/health