server:
  port: ${SERVER_PORT:8095}

#hcx headers
protocol:
  headers:
    mandatory: ${protocol_mandatory_headers:x-hcx-sender_code, x-hcx-recipient_code, x-hcx-api_call_id, x-hcx-timestamp, x-hcx-correlation_id}
    optional: ${protocol_optional_headers:x-hcx-workflow_id, x-hcx-debug_flag, x-hcx-error_details, x-hcx-debug_details, x-hcx-status}
headers:
  jose: ${jose_headers:alg, enc}

redirect:
  apis: ${redirect_apis:/v1/coverageeligibility/on_check, /v1/preauth/on_submit, /v1/claim/on_submit}
  roles: ${redirect_roles:payor, agency.tpa}
  headers:
    mandatory: ${redirect_mandatory_headers:x-hcx-sender_code, x-hcx-recipient_code, x-hcx-api_call_id, x-hcx-timestamp, x-hcx-correlation_id}
    optional: ${redirect_optional_headers:x-hcx-workflow_id, x-hcx-status, x-hcx-redirect_to}

timestamp:
  range: ${timestamp_range:10000}

allowedEntitiesForForward: ${allowedEntitiesForForward:coverageeligibility, preauth, claim}
allowedRolesForForward: ${allowedRolesForForward:payor, agency.tpa}

jwt:
  enabled: ${JWT_ENABLED:true}
  issuer: ${JWT_ISSUER:}
  audience: ${JWT_AUDIENCE:}
  jwkUrl: ${JWT_JWK_URL:http://localhost:8080/auth/realms/sunbird-rc/protocol/openid-connect/certs}
  claimsNamespacePath: ${JWT_NS_PATH:$.realm_access.roles}

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}

registry:
  basePath: ${REGISTRY_BASE_PATH:http://a0b2bab079318431d8ca99f1efb1c25c-874274596.ap-south-1.elb.amazonaws.com:8081}

hcx-api:
  basePath: ${HCX_API_BASEPATH:http://localhost:8080}

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: hcx-api-route
          uri: ${HCX_API_BASEPATH:http://localhost:8080}
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - CachingRequestBodyFilter
            - HCXValidationFilter
          predicates:
            - Path=/v1/coverageeligibility/**, /v1/preauth/**, /v1/claim/**, /v1/paymentnotice/**, /v1/hcx/**, /v1/predetermination/**

        - id: hcx-api-route-audit
          uri: ${HCX_API_BASEPATH:http://localhost:8080}
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - CachingRequestBodyFilter
            - AuditValidationFilter
          predicates:
            - Path=/v1/audit/search

        - id: hcx-registry-api-route
          uri: ${HCX_API_BASEPATH:http://localhost:8080}
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
          predicates:
            - Path=/participant/**, /health, /service/health
