server:
  port: ${SERVER_PORT:8082}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}

env: ${ENV:local}

#elasticsearch config
es:
  host: ${es_host:localhost}
  port: ${es_port:9200}

#Audit config
audit:
  index: ${audit_index:onboard_audit}
  alias: ${audit_alias:onboard_audit}

aws:
  accessKey: ${aws_accessKey:}
  accessSecret: ${aws_accessSecret:}
  region: ${aws_region:}

onboarding:
  successURL: ${onboarding_success_url:http://localhost:3000/onboardingsuccess}

email:
  id: ${email_id:test@gmail.com}
  pwd: ${email_pwd:test@123}
  otpSub: ${otp_sub:HCX - Onboarding Started}
  successIdentitySub: ${success_identity_sub:HCX - Identity Verified}
  failedIdentitySub: ${failed_identity_sub:HCX - Identity Verification Failed}
  onboardingSuccessSub: ${onboarding_success_sub:HCX - Onboarding Successful}

hcx-api:
  basePath: ${HCX_API_BASEPATH:http://localhost:8080}

#postgres config
postgres:
  url: ${postgres_url:jdbc:postgresql://localhost:5432/postgres}
  user: ${postgres_user:postgres}
  password: ${postgres_password:postgres}
  onboardingOtpTable: ${onboarding_otp_table:onboarding_otp}
  onboardingTable: ${onboarding_table:onboarding}


otp:
  expiry: ${otp_expiry:600000}
  maxAttempt: ${otp_max_attempt:3}
  maxRegenerate: ${otp_max_regenerate:5}

registry:
  hcxCode: ${registry_hcx_code:1-d2d56996-1b77-4abb-b9e9-0e6e7343c72e}

jwt-token:
  privateKey : ${private_key:test-private-key}
  expiryTime : ${expiry_time:86400000}