#registry
registry:
  basePath: ${registry_basePath:http://hcx-registry.dev.svc.cluster.local:8081}
  hcxcode: ${registry_hcxcode:1-d2d56996-1b77-4abb-b9e9-0e6e7343c72e}

#elasticsearch config
es:
  host: ${es_host:localhost}
  port: ${es_port:9200}

#Audit config
audit:
  index: ${audit_index:hcx_audit}
  alias: ${audit_alias:hcx_audit}

#hcx config
hcx:
  instanceName: ${hcx_instance_name:swasth-hcx}
  urls:
    notallowed: ${not_allowed_urls:http://dev-hcx.swasth.app/api,http://staging-hcx.swasth.app/api}

aws:
  accessKey: ${aws_accessKey:AKIA6I75KJYE2AIRJ24B}
  accessSecret: ${aws_accessSecret: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}
  region: ${aws_region:ap-southeast-1}

email:
  id: ${email_id:contact@hcxprotocol.io}
  pwd: ${email_pwd:swasthdevops}
  otpSubject: ${email_subject:HCX Onboarding Mail}
  otpMessage: ${otp_messsage:Hi User,<br />Please use this OTP for verification:RANDOM_CODE <br /> Use this below link to verify the OTPs:<br /><a href="USER_LINK" target="_blank">Verify OTP</a> <br /> Thanks,<br /> HCX Team}
  prefillUrl: ${email_prefill_url:https://docs.google.com/forms/d/e/1FAIpQLSc1lmHjmsDG-wStSGrKRNoKZoyRApzqy0NO4q0wdFwb9EsEJQ/viewform?usp=pp_url&entry.902795366=primary_email&entry.54643771=primary_mobile}
  otpVerifySubject: ${otp_verify_subject:HCX Participant Onboarded}
  otpVerifyMessage: ${otp_verify_messsage:Hi User,<br /> Please use this participant code with HCX REGISTRY_CODE <br /> Use this below link to update details in registry<br /> <a href="https://forms.gle/cGhvs5yqZxHtza77A" target="_blank">Update Registry</a> <br />NOTE You will not be able to make calls without updating the endPoint and encryption cert path <br />Thanks,<br /> HCX Team}

hcx-api:
  basePath: ${HCX_API_BASEPATH:http://localhost:8080}

#postgres config
postgres:
  url: ${postgres_url:jdbc:postgresql://localhost:5432/postgres}
  user: ${postgres_user:postgres}
  password: ${postgres_password:postgres}
  onboardingOtpTable: ${onboarding_otp_table:onboarding_otp}
  onboardingTable: ${onboarding_table:onboarding}


otp:
  expiry: ${otp_expiry:600000}
  maxAttempt: ${otp_max_attempt:3}