#server:
#  port: ${SERVER_PORT:8082}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}

#registry
registry:
  basePath: ${registry_basePath:http://a0b2bab079318431d8ca99f1efb1c25c-874274596.ap-south-1.elb.amazonaws.com:8081}
  hcxcode: ${registry_hcxcode:1-d2d56996-1b77-4abb-b9e9-0e6e7343c72e}

#elasticsearch config
es:
  host: ${es_host:localhost}
  port: ${es_port:9200}

#Audit config
audit:
  index: ${audit_index:hcx_audit}
  alias: ${audit_alias:hcx_audit}

#hcx config
hcx:
  instanceName: ${hcx_instance_name:swasth-hcx}
  urls:
    notallowed: ${not_allowed_urls:http://dev-hcx.swasth.app/api,http://staging-hcx.swasth.app/api}

aws:
  accessKey: ${aws_accessKey:AKIA6I75KJYE2AIRJ24B}
  accessSecret: ${aws_accessSecret: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}
  region: ${aws_region:ap-southeast-1}

email:
  id: ${email_id:contact@hcxprotocol.io}
  pwd: ${email_pwd:swasthdevops}
  onboardingFailedSub: ${onboarding_failed_sub:HCX Onboarding Failed}
  onboardingFailedMsg: ${onboarding_failed_msg:Hi User,<br/> We are unable to onboard you on to HCX due to:ERROR_MSG.<br/> Thanks,<br/> HCX Team}
  otpSub: ${otp_sub:HCX Onboarding Mail}
  otpMsg: ${otp_msg:Hi User,<br/>Please use this OTP for verification:RANDOM_CODE <br/> Use this below link to verify the OTPs:<br/><a href="USER_LINK" target="_blank">Verify OTP</a> <br/> Thanks,<br/> HCX Team}
  prefillUrl: ${prefill_url:https://docs.google.com/forms/d/e/1FAIpQLSc1lmHjmsDG-wStSGrKRNoKZoyRApzqy0NO4q0wdFwb9EsEJQ/viewform?usp=pp_url&entry.902795366=primary_email&entry.54643771=primary_mobile}
  otpVerifySub: ${otp_verify_sub:HCX Participant Onboarded}
  otpVerifyMsg: ${otp_verify_msg:Hi User,<br/> Please use this participant code with HCX:&nbsp;REGISTRY_CODE <br/> Use this below link to update details in registry<br/> <a href="https://docs.google.com/forms/d/e/1FAIpQLSefK275MU861GCvXK70RnC4V2hM7zVzhSJTgcUiOU5CD_NGpg/viewform?usp=pp_url&entry.599501370=REGISTRY_CODE" target="_blank">Update Registry</a> <br/>NOTE You will not be able to make calls without updating the end point url and encryption cert path in the registry.<br/>Thanks,<br/> HCX Team}
  failedIdentitySub: ${failed_identity_sub:HCX Participant Registry Updated Failed}
  failedIdentityMsg: ${failed_identity_msg:Hi User,<br/>Identity verification is failed. Please do the identity verification, to update the details in the registry.<br/>Thanks,<br/> HCX Team}
  otpFailedSub: ${otp_failed_sub:HCX Verify OTP Failed}
  otpFailedMsg: ${otp_failed_msg:Hi User,<br/> OTP verification failed due to error:ERROR_MSG<br/> Use this below link to regenerate OTPs<br/> <a href="https://docs.google.com/forms/d/e/1FAIpQLSfgJ-ZKBOfdIQMxSCchA4QawP1pnBeaAglRcFMYCOChKYD0KQ/viewform?usp=pp_url&entry.1212464776=primary_email&entry.2080042002=primary_mobile" target="_blank">Regenerate OTPs</a> <br/>Thanks,<br/> HCX Team}
  otpFailedWithoutLinkMsg: ${otp_failed_msg:Hi User,<br/> OTP verification failed due to error:ERROR_MSG<br/>Thanks,<br/> HCX Team}

hcx-api:
  basePath: ${HCX_API_BASEPATH:http://localhost:8080}

#postgres config
postgres:
  url: ${postgres_url:jdbc:postgresql://localhost:5432/postgres}
  user: ${postgres_user:postgres}
  password: ${postgres_password:postgres}
  onboardingOtpTable: ${onboarding_otp_table:onboarding_otp}
  onboardingTable: ${onboarding_table:onboarding}


otp:
  expiry: ${otp_expiry:600000}
  maxAttempt: ${otp_max_attempt:3}