#registry
registry:
  basePath: ${registry_basePath:http://a0b2bab079318431d8ca99f1efb1c25c-874274596.ap-south-1.elb.amazonaws.com:8081}
  hcxcode: ${registry_hcxcode:1-d2d56996-1b77-4abb-b9e9-0e6e7343c72e}

#elasticsearch config
es:
  host: ${es_host:localhost}
  port: ${es_port:9200}

#Audit config
audit:
  index: ${audit_index:hcx_audit}
  alias: ${audit_alias:hcx_audit}

#hcx config
hcx:
  instanceName: ${hcx_instance_name:swasth-hcx}
  urls:
    notallowed: ${not_allowed_urls:http://dev-hcx.swasth.app/api,http://staging-hcx.swasth.app/api}

aws:
  accessKey: ${aws_accessKey:AKIAQPEQMNBRMBH7HZN4}
  accessSecret: ${aws_accessSecret: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}
  region: ${aws_region:ap-southeast-1}