server:
  port: ${SERVER_PORT:8082}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}

env: ${env:local}

#elasticsearch config
es:
  host: ${es_host:localhost}
  port: ${es_port:9200}

#Audit config
audit:
  index: ${audit_index:hcx_audit}
  alias: ${audit_alias:hcx_audit}

aws:
  accessKey: ${aws_accessKey:AKIA6I75KJYE2AIRJ24B}
  accessSecret: ${aws_accessSecret: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}
  region: ${aws_region:ap-southeast-1}

email:
  id: ${email_id:contact@hcxprotocol.io}
  pwd: ${email_pwd:swasthdevops}
  onboardingFailedSub: ${onboarding_failed_sub:HCX Onboarding Failed}
  onboardingFailedMsg: ${onboarding_failed_msg:Hi User,<br/> We are unable to onboard you on to HCX due to:ERROR_MSG.<br/> Thanks,<br/> HCX Team}
  otpSub: ${otp_sub:HCX Onboarding Mail}
  otpMsg: ${otp_msg:Hi User,<br/>Please use this OTP for verification:RANDOM_CODE <br/> Use this below link to verify the OTPs:<br/><a href="USER_LINK" target="_blank">Verify OTP</a> <br/> Thanks,<br/> HCX Team}
  prefillUrl: ${prefill_url:https://script.google.com/macros/s/AKfycbyh82T-2Jb4UdZmPnA7w7rd9CCEz-Zr0NbV6fVPMkkFQf1FYQU2u1L5rEXaKRAu7azd/exec?primary_email=USER_MAIL&primary_mobile=PHONE}
  otpVerifySub: ${otp_verify_sub:HCX Participant Onboarded}
  otpVerifyMsg: ${otp_verify_msg:Hi User,<br/> Please use this participant code with HCX:&nbsp;REGISTRY_CODE <br/> Use this below link to update details in registry<br/> <a href="https://script.google.com/macros/s/AKfycbwwKSpZ3kqDE0Gg9jSJxBF2UyHeVFcMF7j7n8OqUOgtq4UexmFDp5v9_nl2eZKEkrowDA/exec?participant_code=REGISTRY_CODE" target="_blank">Update Registry</a> <br/>NOTE You will not be able to make calls without updating the end point url and encryption cert path in the registry.<br/>Thanks,<br/> HCX Team}
  failedIdentitySub: ${failed_identity_sub:HCX Participant Registry Updated Failed}
  failedIdentityMsg: ${failed_identity_msg:Hi User,<br/>Identity verification is failed. Please do the identity verification, to update the details in the registry.<br/>Thanks,<br/> HCX Team}
  otpFailedSub: ${otp_failed_sub:HCX Verify OTP Failed}
  otpFailedMsg: ${otp_failed_msg:Hi User,<br/> OTP verification failed due to error:ERROR_MSG<br/> Use this below link to regenerate OTPs<br/> <a href="https://script.google.com/macros/s/AKfycbxdkdENBMDD74wHvTPpGHoZVqXlsoKr3iy59Hmk7Q1IfbZOlCvnUmsgBvOeVZqYCKaeFw/exec?primary_email=USER_MAIL&primary_mobile=PHONE" target="_blank">Regenerate OTPs</a> <br/>Thanks,<br/> HCX Team}
  otpFailedWithoutLinkMsg: ${otp_failed_msg:Hi User,<br/> OTP verification failed due to error:ERROR_MSG<br/>Thanks,<br/> HCX Team}
  registryUpdateSub: ${registry_update_sub:HCX Registry Updated}
  registryUpdateMsg: ${registry_update_msg:Hi User,<br/> Registry has been updated for your participant code:REGISTRY_CODE <br/> Thanks,<br/> HCX Team}

hcx-api:
  basePath: ${HCX_API_BASEPATH:http://localhost:8080}

#postgres config
postgres:
  url: ${postgres_url:jdbc:postgresql://localhost:5432/postgres}
  user: ${postgres_user:postgres}
  password: ${postgres_password:postgres}
  onboardingOtpTable: ${onboarding_otp_table:onboarding_otp}
  onboardingTable: ${onboarding_table:onboarding}


otp:
  expiry: ${otp_expiry:600000}
  maxAttempt: ${otp_max_attempt:3}