#registry
registry:
  basePath: ${registry_basePath:http://hcx-registry.dev.svc.cluster.local:8081}
  hcxcode: ${registry_hcxcode:1-d2d56996-1b77-4abb-b9e9-0e6e7343c72e}

#elasticsearch config
es:
  host: ${es_host:localhost}
  port: ${es_port:9200}

#Audit config
audit:
  index: ${audit_index:hcx_audit}
  alias: ${audit_alias:hcx_audit}

#hcx config
hcx:
  instanceName: ${hcx_instance_name:swasth-hcx}
  urls:
    notallowed: ${not_allowed_urls:http://dev-hcx.swasth.app/api,http://staging-hcx.swasth.app/api}

aws:
  accessKey: ${aws_accessKey:AKIA6I75KJYE2AIRJ24B}
  accessSecret: ${aws_accessSecret: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}
  region: ${aws_region:ap-southeast-1}

email:
  id: ${email_id:contact@hcxprotocol.io}
  pwd: ${email_pwd:swasthdevops}
  subject: ${email_subject:HCX Onboarding Mail}
  message: ${email_messsage:Hi User,<br />Please use this OTP for verification:RANDOM_CODE <br /> Use this below link to verify the OTPs:<br /><a href="USER_LINK" target="_blank">Verify OTP</a> <br /> Thanks,<br /> HCX Team}