#kafka configuration
bootstrap-servers: ${bootstrap_servers:localhost:9092}

kafka:
  denormaliser:
    topic: ${kafka_topic:test}
    key: ${kafka_key:test}

#hcx headers
protocol:
  mandatory:
    headers: ${protocol_mandatory_headers:x-hcx-sender_code, x-hcx-recipient_code, x-hcx-request_id, x-hcx-correlation_id, x-hcx-timestamp, x-hcx-status, jws_header, jwe_header}
  optional:
    headers: ${protocol_optional_headers:x-hcx-workflow_id, x-hcx-debug_flag, x-hcx-error_details, x-hcx-debug_details}
domain:
  headers: ${domain_headers:use_case_name, parameter_name}
jose:
  headers: ${jose_headers:alg, enc}

#hcx payload properties
payload:
  mandatory:
    properties: ${payload_mandatory_properties:protected, encrypted_key, aad, iv, ciphertext, tag}