#kafka configuration
bootstrap-servers: ${bootstrap_servers:localhost:9092}

kafka:
  topic:
    payload: ${kafka_payload_topic:local.hcx.request.payload}
    coverageeligibility: ${kafka_coverageeligibility_topic:hcx.request.coverageeligibility}
    preauth: ${kafka_preauth_topic:hcx.request.preauth}
    claim: ${kafka_claim_topic:hcx.request.claim}
    payment: ${kafka_payment_topic:hcx.request.payment}

service:
  mode: ${service_mode:gateway}

#postgres configuration
postgres:
  url: ${postgres_url:jdbc:postgresql://localhost:5432/postgres}
  username: ${postgres_username:postgres}
  password: ${postgres_password:postgres}
  tablename: ${postgres_tablename:payload}

#hcx headers
protocol:
  headers:
    mandatory: ${protocol_mandatory_headers:x-hcx-sender_code, x-hcx-recipient_code, x-hcx-request_id, x-hcx-correlation_id, x-hcx-timestamp, x-hcx-status, jws_header, jwe_header}
    optional: ${protocol_optional_headers:x-hcx-workflow_id, x-hcx-debug_flag, x-hcx-error_details, x-hcx-debug_details}
headers:
  domain: ${domain_headers:use_case_name, parameter_name}
  jose: ${jose_headers:alg, enc}

#hcx payload properties
payload:
  mandatory:
    properties: ${payload_mandatory_properties:protected, encrypted_key, aad, iv, ciphertext, tag}