name: Onboarding App Deploy to S3

on:
  push:
    workflow_dispatch:
    branches:
      - main
      - sprint-*
      - onboarding-app*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

#      - name: Use Node.js 19.x
#        uses: actions/setup-node@v3
#        with:
#          node-version: 19.x
#          cache: 'npm'
#          cache-dependency-path: onboarding-app/package-lock.json

      - name: Install dependencies
        run: |
          cd onboarding-app
          npm ci

      - name: Build the app
        env:
          CI: false
        run: |
          cd onboarding-app
          npm run build

      - name: Configure AWS credentials
        run: |
         cd onboarding-app
         aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to S3
        run: |
          cd onboarding-app
          aws s3 sync build/ s3://dev-hcx-certificates --acl public-read --region ap-south-1